### ISSUE TITLE
Dockerfile issues

### ISSUE THREAD

**Issue by AlessioQuercia** [mansheej/data_diet#2]
I installed the docker repository and run it. Then I tried running the following command as a test:
`python scripts/get_run_score.py . test 10 10 10 grad_norm` 
and got the following error:
```
Traceback (most recent call last):
  File "scripts/get_run_score.py", line 3, in <module>
    from data_diet.data import load_data
  File "/data_diet/scripts/data_diet/data.py", line 1, in <module>
    from jax import random
  File "/usr/local/lib/python3.7/dist-packages/jax/__init__.py", line 37, in <module>
    from jax import config as _config_module
  File "/usr/local/lib/python3.7/dist-packages/jax/config.py", line 18, in <module>
    from jax._src.config import config
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/lib/__init__.py", line 90, in <module>
    minimum_jaxlib_version=jax.version._minimum_jaxlib_version)
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/lib/__init__.py", line 76, in check_jaxlib_version
    raise RuntimeError(msg)
RuntimeError: jaxlib is version 0.1.65, but this version of jax requires version >= 0.1.74.
```
Then I updated jax to 0.1.74, run again the test command and got this other error:
```
Traceback (most recent call last):
  File "scripts/get_run_score.py", line 3, in <module>
    from data_diet.data import load_data
  File "/data_diet/scripts/data_diet/data.py", line 1, in <module>
    from jax import random
  File "/usr/local/lib/python3.7/dist-packages/jax/__init__.py", line 22, in <module>
    from .api import (
  File "/usr/local/lib/python3.7/dist-packages/jax/api.py", line 38, in <module>
    from . import core
  File "/usr/local/lib/python3.7/dist-packages/jax/core.py", line 31, in <module>
    from . import dtypes
  File "/usr/local/lib/python3.7/dist-packages/jax/dtypes.py", line 31, in <module>
    from .lib import xla_client
  File "/usr/local/lib/python3.7/dist-packages/jax/lib/__init__.py", line 54, in <module>
    from jaxlib import pytree
ImportError: cannot import name 'pytree' from 'jaxlib' (/usr/local/lib/python3.7/dist-packages/jaxlib/__init__.py)
```

Am I doing something wrong or are the requirements around jax broken?

**Comment by julien-blanchon** [comment]
This repo si not working at all !

**Comment by sbhavani** [comment]
I'd recommend updating the Dockerfile to use [JAX Toolbox](https://github.com/NVIDIA/JAX-Toolbox/pkgs/container/jax) containers which are validated with a nightly CI on NVIDIA GPUs.
